# 
# Copyright 2024 Cypriot Free Software Foundation
#
# Permission is hereby granted, free of charge, 
# to any person obtaining a copy of this software and associated documentation files (the “Software”), 
# to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, 
# sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
# subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

name: "release-js"  

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
        - name: Checkout current branch
          uses: actions/checkout@v4

        - name: "Setup Node"
          uses: actions/setup-node@v4
          with:
            node-version: 21
            registry-url: 'https://registry.npmjs.org'

        - name: "Install npm dependencies"
          run: npm ci

        - name: commit built package.json
          uses: actions-x/commit@v6
          with:
            email: actions@github.com
            name: Mark Release as prerelease for npm
            files: package.json
            token: ${{ secrets.MY_SECRET_TOKEN }}
            force: true

        - name: version
          id: version
          run: |
            echo version=$(npm run version --silent) >> "$GITHUB_OUTPUT"

        - name: Tag version
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            custom_tag: ${{ steps.version.outputs.version }}
        
        - id: npm-publish
          name: publish into npmjs
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_KEY }}
          run:
            npm publish